import { checkLicense } from '@/lib/license';
import { AlertTriangle, Info, CheckCircle } from 'lucide-react';

export default async function ProjectDiffPage({ params }: { params: { id: string } }) {
  const license = await checkLicense();
  const { id } = params;

  // Mocked data for the demo
  const isDemo = id === 'demo';

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold">Project: {isDemo ? 'Demo Local Spec' : id}</h1>
          <p className="text-gray-500 mt-1">Comparing <code>baseline.yaml</code> vs <code>current.yaml</code></p>
        </div>
        <div className="flex space-x-2">
          {license.tier === 'demo' && (
            <span className="bg-purple-100 text-purple-800 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider">
              DEMO – NOT FOR PRODUCTION
            </span>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Summary */}
        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-100 md:col-span-1 space-y-4">
          <h2 className="text-lg font-semibold border-b pb-2">Diff Summary</h2>
          <div className="flex items-center text-red-600">
            <AlertTriangle className="w-5 h-5 mr-2" />
            <span className="font-medium">1 Breaking Change</span>
          </div>
          <div className="flex items-center text-blue-600">
            <Info className="w-5 h-5 mr-2" />
            <span className="font-medium">1 Minor Change</span>
          </div>
          <div className="flex items-center text-gray-600">
            <CheckCircle className="w-5 h-5 mr-2" />
            <span className="font-medium">0 Patches</span>
          </div>
        </div>

        {/* Changelog details */}
        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-100 md:col-span-2">
          <h2 className="text-lg font-semibold border-b pb-2 mb-4">Changelog Report</h2>
          
          <div className="space-y-6">
            <div className="p-4 border border-red-200 bg-red-50 rounded-md">
              <h3 className="font-bold text-red-800 flex items-center mb-2">
                <AlertTriangle className="w-4 h-4 mr-2" /> Breaking Changes
              </h3>
              <ul className="list-disc list-inside text-sm text-red-900 space-y-1">
                <li><code>/users (GET)</code>: Changed response schema type for property <code>id</code> from <strong>integer</strong> to <strong>string</strong>.</li>
              </ul>
            </div>

            <div className="p-4 border border-blue-200 bg-blue-50 rounded-md">
              <h3 className="font-bold text-blue-800 flex items-center mb-2">
                <Info className="w-4 h-4 mr-2" /> Minor Changes
              </h3>
              <ul className="list-disc list-inside text-sm text-blue-900 space-y-1">
                <li><code>/users (POST)</code>: Added new endpoint <em>"Create a user"</em>.</li>
              </ul>
            </div>
          </div>

          {license.tier === 'demo' && (
            <div className="mt-8 pt-4 border-t border-gray-100 text-center text-xs text-gray-400">
              * This changelog was generated by SpecSentry (DEMO - NOT FOR PRODUCTION) *
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
